config/routes.rb
Rails.application.routes.draw do
     resources :users

     get 'sessions/new'
     root "top#index"

     get    'users'  => 'users#index'
     get    'user'  => 'users#other'
     get    'signup'  => 'users#new'
     get    'login'   => 'sessions#new'
     post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
     end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base

# 制限
 has_secure_password
  validates :userid,  presence: true
  validates :name,  presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }

# 与えられた文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

# ランダムなトークンを返す
def User.new_token
  SecureRandom.urlsafe_base64
end

# ログイン情報を記録
def remember
  self.remember_token = User.new_token
  update_attribute(:remember_digest, User.digest(remember_token))
end

# 渡されたトークンがダイジェストと一致したらtrueを返す
def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
end

# ログアウト
def forget
  update_attribute(:remember_digest, nil)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # ログインをしているか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

#ログイン
  def create
    user = User.find_by(userid: params[:session][:userid].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:info] = "ログインしました"
      redirect_to user

    else
      flash.now[:danger] = 'ユーザーIDもしくはパスワードが間違っています'
      render :new
    end
  end

#ログアウト
  def destroy
    log_out if logged_in?
    flash[:notice] = "ログアウトしました"
    redirect_to root_url
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
  def profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

#ユーザー一覧
   def index
      @users = User.all
      end

#マイページ
   def show
     @user = User.find(params[:id])
   end

#新規作成
   def new
     @user = User.new
   end

#プロフィール編集
   def edit
     @user = User.find(params[:id])
   end

#アカウント作成
   def create
     @user = User.new(user_params)
     if @user.save
       log_in @user
       flash[:success] = "ようこそ！"
       redirect_to @user
     else
       render 'new'
     end
   end

#プロフィール更新
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
    render 'edit'
  end
  end

  def destroy
 @user = User.find(params[:id])
 @user.destroy
 redirect_to login_url
 end

#ログインしているかを確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
end

 private
 def user_params
  params.require(:user).permit(:userid,:name,:email,:password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
     base_title = "アプリ名" # 自分のアプリ名を設定する
     if page_title.empty?
       base_title
     else
       "#{page_title} | #{base_title}"
     end
   end
 end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッション情報を記録
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
    def logged_in?
      !current_user.nil?
    end

def forget(user)
  user.forget
  cookies.delete(:user_id)
  cookies.delete(:remember_token)
end

# 現在のユーザーがログアウトする
def log_out
  forget(current_user)
  session.delete(:user_id)
  @current_user = nil
end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
  <div class="container">
        <%= link_to "Rails-myapp", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
        <li><%= link_to "マイページ", current_user %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails-myapp</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/top/index.html.erb
<div class="center jumbotron">
  <h1>ようこそ！</h1>

  <a><%= link_to "ログイン", login_path, class: "btn btn-info" %></a>
</div>

app/views/top/profile.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= image_tag @user.image_url(:thumb) %>
        <h2><%= @user.name %></h2>
        <h2><%= @user.gender %></h2>
      </h1>
    </section>
  </aside>
</div>

app/views/users/edit.html.erb
<div class="container" style="padding-top: 60px;">
  <h1>プロフィール編集</h1>
  <div class="row">
    <%= form_for @user do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <!-- マイページ編集項目 -->
    <div class="col-md-8 col-md-offset-3">
    <form class="form-horizontal" role="form">
      <div class="form-group">
        <label class="col-lg-3 control-label">名前:</label>
        <div class="col-lg-8">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-3 control-label">メールアドレス:</label>
        <div class="col-lg-8">
          <%= f.email_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-3 control-label">パスワード:</label>
        <div class="col-lg-8">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
     <label class="col-lg-3 control-label">パスワードを再入力:</label>
     <div class="col-lg-8">
       <%= f.password_field :password_confirmation, class: 'form-control' %>
     </div>
   </div>
      <div class="form-group">
        <label class="col-md-3 control-label"></label>
        <div class="col-md-8">
          <%= f.submit "送信", class: "btn btn-primary" %>
            <span></span>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div class="container">
  <form class="form-inline">
    <div class="form-group">

<div class="profile_list">
  <div class="container">
    <div class="table-responsive">
      <table class="table table-bordered">
        <theader>
          <tr>
            <th><%='ID' %></th>
            <th><%='名前' %></th>
            <th><%='ユーザーID' %></th>
            <th><%='メールアドレス'%></th>
          </tr>
        </theader>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td> <a href="/users/<%=user.id%>"><%= user.name %></a>
              </td>
              <td><%= user.userid %></td>
              <td><%= user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "sign up") %>
  <h1>新規作成</h1>
  <div class="row">
      <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <!-- 新規作成項目 -->
      <div class="col-md-8 col-md-offset-3">
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <label class="col-lg-3 control-label">ユーザーID:</label>
          <div class="col-lg-8">
            <%= f.text_field :userid, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">名前:</label>
          <div class="col-lg-8">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">メールアドレス:</label>
          <div class="col-lg-8">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">パスワード:</label>
          <div class="col-lg-8">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">パスワードを再入力:</label>
          <div class="col-lg-8">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <%= f.submit "送信", class: "btn btn-primary" %>
            <span></span>
          </div>
        </div>
      </form>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
<h1>マイページ</h1>
<% else %>
<% end %>
<div class="container">
  <div class="jumbotron">
    <div class="row">

      <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
        <div class="container" style="border-bottom:1px solid black">
          <h3><%= @user.name %></h3>
        </div>
        <hr>
        <div class=" col-md-9 col-lg-9 ">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <% if current_user.id == @user.id %>
                <td>ユーザーID:</td>
                <td><%= @user.userid %></td>
                <% else %>
                <% end %>
              </tr>
              <tr>
                <td>メールアドレス:</td>
                <td><%= @user.email %></td>
              </tr>
              <tr>
            </tbody>
          </table>
<% if current_user.id == @user.id %>
          <%= link_to '編集', edit_user_path(@user), class: "btn btn-info" %>
          |
          <%= link_to '削除', user_path(@user), :method => :delete, class: "btn btn-danger", data: {confirm: '削除しますか？'} %>
          <% else %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
  </div>